# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f17365a1fa7a6cb1fc2a60c3a8163efe453f388ded887801b480d32fef352c76415ef960047e9b570b15b178e8adec3762581b7ada304d596b372a9c73ee16b

test:
  secret_key_base: 0936527b7bde02e42aab0189c37a45dbbc817d752ee4a47c7d932ceffe9f6c7a340ea7e290dfeca1298f9ac777798914636b50625f31c3b11d90691b487ac706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
